{% set name = "helipad" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/helipad-{{ version }}.tar.gz
  sha256: a6c63e0704c2fc09cc7acfef25c637b8587d11860ccf5c77524ed33038eba333

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10
    - matplotlib-base
    - pillow <=10.0.0 # Not necessary explicitly, but pin version because build fails on Conda with higher versions (missing DLL?). Check again next time
    - pandas
    - networkx

test:
  imports:
    - helipad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://helipad.dev
  summary: An agent-based modeling framework for Python with a shallow learning curve and powerful visualization capabilities.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/charwick/helipad/
  doc_url: https://helipad.dev/functions/

extra:
  recipe-maintainers:
    - charwick