{% set name = "helipad" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/helipad-{{ version }}.tar.gz
  sha256: 5b5801daa7fbe8d435dc96504b65eed5670a21709845b113e17453877b366242

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base
    - pandas
    - networkx

test:
  imports:
    - helipad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://helipad.dev
  summary: An agent-based modeling framework for Python with a shallow learning curve and powerful visualization capabilities.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/charwick/helipad/
  doc_url: https://helipad.dev/functions/

extra:
  recipe-maintainers:
    - charwick